AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Region:
    Type: String
    Default: us-east-1
  Environment:
    Type: String
    Description: Environemnt for the Stack
    Default: development
  FunctionName:
    Type: String
    Description: Name of the lambda function
    Default: item-api
  DeploymentBucketName:
    Type: String
    Description: Bucket used for deployment and data storage
    Default: cf-item-api-deployment
  DeploymentFileName:
    Type: String
    Default: index.zip

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 
                  Fn::Sub: "arn:aws:logs:${Region}:${AWS::AccountId}:*"

  ItemApiLambdaFunctionUrlPublicPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: ItemApiFunction
      Principal: '*'
      Action: 'lambda:InvokeFunctionUrl'
      FunctionUrlAuthType: NONE

  ItemApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 
        Fn::Sub: "${FunctionName}-${Environment}"
      Handler: index.handler
      Role:
        Fn::GetAtt: LambdaExecutionRole.Arn
      Code:
        S3Bucket:
          Ref: DeploymentBucketName
        S3Key:
          Ref: DeploymentFileName
      Runtime: nodejs22.x
      Timeout: 60
      MemorySize: 128
      Architectures:
        - arm64
      Environment:
        Variables:
          Environment:
            Fn::Sub: "${Environment}"

  ItemApiUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn:
        Ref: ItemApiFunction
      AuthType: NONE

Outputs:
  ItemApiFunction:
    Description: 'ItemApiFunction Arn'
    Value:
      Fn::GetAtt: ItemApiFunction.Arn
  ItemApiUrl:
    Description: 'ItemApiUrl'
    Value:
      Fn::GetAtt: ItemApiUrl.FunctionUrl
