AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-ts

  Sample SAM Template for sam-app-ts
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  RestApiFunction:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../src/api/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        # - arm64
        - x86_64
      Events:
        # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        Api:
          Type: HttpApi # Api (Api Gateway) or HttpApi (Api Gateway v2)
          Properties:
            Path: /api/{resource+}
            Method: ANY
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - index.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RestApiApi:
    Description: "API Gateway endpoint URL for Prod stage for RestApi function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/item"
  RestApiFunction:
    Description: "RestApi Lambda Function ARN"
    Value: !GetAtt RestApiFunction.Arn
  RestApiFunctionIamRole:
    Description: "Implicit IAM Role created for RestApi function"
    Value: !GetAtt RestApiFunctionRole.Arn
